# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "DOCKER_CONTAINER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"vrn" VARCHAR NOT NULL,"status" VARCHAR NOT NULL,"imageRepo" VARCHAR NOT NULL,"imageVersion" VARCHAR NOT NULL,"ports" VARCHAR NOT NULL,"serviceId" BIGINT NOT NULL,"created_at" TIMESTAMP NOT NULL);
create table "DOCKER_IMAGE" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"repo" VARCHAR NOT NULL,"version" VARCHAR NOT NULL,"arguments" VARCHAR NOT NULL);
create table "ENVIRONMENT" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"state" VARCHAR NOT NULL);
create table "JOB" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"status" VARCHAR NOT NULL,"priority" INTEGER NOT NULL,"payload" VARCHAR NOT NULL,"queue" VARCHAR NOT NULL,"created_at" TIMESTAMP NOT NULL,"updated_at" TIMESTAMP NOT NULL);
create table "JOB_EVENTS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"status" VARCHAR NOT NULL,"payload" VARCHAR NOT NULL,"jobId" BIGINT NOT NULL,"timestamp" TIMESTAMP NOT NULL);
create table "SERVICES" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"version" VARCHAR NOT NULL);
create table "ServiceInstanceS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"port" INTEGER NOT NULL,"state" VARCHAR NOT NULL,"vrn" VARCHAR NOT NULL,"environmentId" BIGINT NOT NULL,"serviceTypeId" BIGINT NOT NULL);
alter table "DOCKER_CONTAINER" add constraint "SERVICE_FK" foreign key("serviceId") references "ServiceInstanceS"("id") on update NO ACTION on delete NO ACTION;
alter table "JOB_EVENTS" add constraint "JOB_FK" foreign key("jobId") references "JOB"("id") on update NO ACTION on delete NO ACTION;
alter table "ServiceInstanceS" add constraint "ENV_FK" foreign key("environmentId") references "ENVIRONMENT"("id") on update NO ACTION on delete NO ACTION;
alter table "ServiceInstanceS" add constraint "SERVICE_FK" foreign key("serviceTypeId") references "SERVICES"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "ServiceInstanceS" drop constraint "ENV_FK";
alter table "ServiceInstanceS" drop constraint "SERVICE_FK";
alter table "JOB_EVENTS" drop constraint "JOB_FK";
alter table "DOCKER_CONTAINER" drop constraint "SERVICE_FK";
drop table "ServiceInstanceS";
drop table "SERVICES";
drop table "JOB_EVENTS";
drop table "JOB";
drop table "ENVIRONMENT";
drop table "DOCKER_IMAGE";
drop table "DOCKER_CONTAINER";

