# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "DOCKER_CONTAINER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"created" BIGINT NOT NULL,"ports" VARCHAR NOT NULL);
create table "DOCKER_IMAGE" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"repo" VARCHAR NOT NULL,"version" VARCHAR NOT NULL,"arguments" VARCHAR NOT NULL);
create table "JOB" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"status" VARCHAR NOT NULL,"priority" INTEGER NOT NULL,"payload" VARCHAR NOT NULL,"queue" VARCHAR NOT NULL,"created_at" TIMESTAMP NOT NULL,"updated_at" TIMESTAMP NOT NULL);
create table "JOB_EVENTS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"status" VARCHAR NOT NULL,"payload" VARCHAR NOT NULL,"jobId" BIGINT NOT NULL,"timestamp" TIMESTAMP NOT NULL);
alter table "JOB_EVENTS" add constraint "JOB_FK" foreign key("jobId") references "JOB"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "JOB_EVENTS" drop constraint "JOB_FK";
drop table "JOB_EVENTS";
drop table "JOB";
drop table "DOCKER_IMAGE";
drop table "DOCKER_CONTAINER";

