# Job schema

# --- !Ups

create table "JOB" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "status" VARCHAR NOT NULL,
  "priority" BIGINT NOT NULL DEFAULT 0,
  "payload" CLOB,
  "created_at" TIMESTAMP,
  "updated_at" TIMESTAMP);


# --- !Downs

DROP TABLE "JOB";
